# This script constructs a semi-manual summary of the analyses of
# problematic cluster annotations in the IBA SE data for
# Lepidoptera. See the analysis documents for more information
# on the interpretation for each cluster.

# Get basic information from bold_probs.tsv
D <- read.table("../output_tables/bold_probs.tsv")
res <- D[D$SE_occurrence=="Bofast och reproducerande" & D$dyntaxa_match=="Exact",c("cluster","dyntaxa_name")]

# Add information from the manual analysis of remaining bold_probs clusters
res <- rbind(res, c(cluster="Tortricidae_cluster84",dyntaxa_name="Cochylis dubitana"))
res <- rbind(res, c("Geometridae_cluster73", "Idaea deversaria"))
res <- rbind(res, c("Geometridae_cluster51", "Scopula ternata"))
res <- rbind(res, c("Geometridae_cluster92", "Eupithecia analoga"))
res <- rbind(res, c("Drepanidae_cluster5", "Falcaria lacertinaria"))
res <- rbind(res, c("Sphingidae_cluster4", "Sphinx pinastri"))
res <- rbind(res, c("Noctuidae_cluster165", "Leucania dia"))
res <- rbind(res, c("Noctuidae_cluster192", "Ceramica pisi"))
res <- rbind(res, c("Gracillariidae_cluster68", "Caloptilia jurateae"))
res <- rbind(res, c("Noctuidae_cluster98", "Enargia paleacea"))
res <- rbind(res, c("Hesperiidae_cluster4", "Pyrgus malvae"))
res <- rbind(res, c("Tortricidae_cluster131", "Pammene clanculana"))
res <- rbind(res, c("Erebidae_cluster47", "Spilarctia lutea"))
res <- rbind(res, c("Tortricidae_cluster135", "Pammene obscurana"))
res <- rbind(res, c("Tineidae_cluster7", "Nemapogon wolffiellus"))
res <- rbind(res, c("Noctuidae_cluster65", "Papestra biren"))
res <- rbind(res, c("Tortricidae_cluster244", "Acleris implexana"))
res <- rbind(res, c("Tortricidae_cluster83", "Argyrotaenia ljungiana"))
res <- rbind(res, c("Momphidae_cluster13", "Mompha sexstrigella"))
res <- rbind(res, c("Tortricidae_cluster180", "Acleris effractana"))
res <- rbind(res, c("Elachistidae_cluster24", "Elachista serricornis"))
res <- rbind(res, c("Tortricidae_cluster14", "Phiaris metallicana"))
res <- rbind(res, c("Pyralidae_cluster5", "Ortholepis vacciniella"))


# Add in taxa from dyntaxa misses file
# Note that A. martinii is referred to incorrectly in DynTaxa as A. bifractella
# The dyntaxa name should have been A. martinii, and this is the name used here
# to get the correct match to the GBIF taxonomy
res <- rbind(res, c("Tortricidae_cluster9", "Phiaris bipunctana"))
res <- rbind(res, c("Tortricidae_cluster49", "Cochylis nana"))
res <- rbind(res, c("Tortricidae_cluster192", "Phiaris heinrichana"))
res <- rbind(res, c("Tortricidae_cluster266", "Cochylis atricapitana"))
res <- rbind(res, c("Crambidae_cluster2", "Crambus lathoniellus"))
res <- rbind(res, c("Crambidae_cluster6", "Agriphila tristella"))
res <- rbind(res, c("Crambidae_cluster9", "Catoptria margaritella"))
res <- rbind(res, c("Crambidae_cluster30", "Scoparia subfusca"))
res <- rbind(res, c("Crambidae_cluster40", "Platytes cerussella"))
res <- rbind(res, c("Geometridae_cluster140", "Euphyia unangulata"))
res <- rbind(res, c("Geometridae_cluster155", "Thera obeliscata"))
res <- rbind(res, c("Geometridae_cluster181", "Eupithecia groenblomi"))
res <- rbind(res, c("Geometridae_cluster183", "Eupithecia groenblomi"))
res <- rbind(res, c("Noctuidae_cluster35", "Xestia arctica"))
res <- rbind(res, c("Noctuidae_cluster43", "Xestia baja"))
res <- rbind(res, c("Noctuidae_cluster114", "Xestia stigmatica"))
res <- rbind(res, c("Noctuidae_cluster154", "Xestia rhaetica"))
res <- rbind(res, c("Gelechiidae_cluster32", "Eulamprotes atrella"))
res <- rbind(res, c("Gelechiidae_cluster38", "Eulamprotes unicolorella"))
res <- rbind(res, c("Gelechiidae_cluster53", "Apodia martinii"))
res <- rbind(res, c("Gelechiidae_cluster54", "Syncopacma taeniolella"))
res <- rbind(res, c("Gelechiidae_cluster61", "Syncopacma cinctella"))
res <- rbind(res, c("Gelechiidae_cluster92", "Syncopacma karvoneni"))
res <- rbind(res, c("Gelechiidae_cluster112", "Eulamprotes wilkella"))
res <- rbind(res, c("Gelechiidae_cluster113", "Eulamprotes superbella"))
res <- rbind(res, c("Gelechiidae_cluster124", "Monochroa palustrella"))
res <- rbind(res, c("Nymphalidae_cluster6", "Vanessa atalanta"))
res <- rbind(res, c("Nymphalidae_cluster7", "Vanessa cardui"))
res <- rbind(res, c("Elachistidae_cluster33", "Agonopterix angelicella"))
res <- rbind(res, c("Glyphipterigidae_cluster2", "Acrolepia autumnella"))
res <- rbind(res, c("Adelidae_cluster1", "Adela viridella"))
res <- rbind(res, c("Adelidae_cluster14", "Nemophora bellela"))
res <- rbind(res, c("Yponomeutidae_cluster17", "Yponomeuta sedellus"))
res <- rbind(res, c("Yponomeutidae_cluster19", "Euhyponomeutoides albithoracellus"))
res <- rbind(res, c("Gracillariidae_cluster38", "Phyllonorycter lautellus"))
res <- rbind(res, c("Gracillariidae_cluster58", "Phyllocnistis labyrinthella"))
res <- rbind(res, c("Gracillariidae_cluster67", "Phyllonorycter klemannella"))
res <- rbind(res, c("Lasiocampidae_cluster4", "Dendrolimus pini"))
res <- rbind(res, c("Lasiocampidae_cluster5", "Poecilocampa populi"))
res <- rbind(res, c("Lasiocampidae_cluster7", "Trichiura crataegi"))
res <- rbind(res, c("Psychidae_cluster3", "Taleporia politella"))
res <- rbind(res, c("Lycaenidae_cluster13", "Satyrium w-album"))
res <- rbind(res, c("Pterophoridae_cluster9", "Gillmeria tetradactyla"))
res <- rbind(res, c("Momphidae_cluster5", "Mompha divisella"))
res <- rbind(res, c("Nepticulidae_cluster1", "Ectoedemia weaveri"))
res <- rbind(res, c("Nepticulidae_cluster5", "Stigmella nylandriella"))
res <- rbind(res, c("Nepticulidae_cluster26", "Ectoedemia atrifrontella"))
res <- rbind(res, c("Nepticulidae_cluster46", "Ectoedemia septembrella"))
res <- rbind(res, c("Nepticulidae_cluster57", "Ectoedemia amani"))
res <- rbind(res, c("Nepticulidae_cluster71", "Ectoedemia albibimaculella"))
res <- rbind(res, c("Nepticulidae_cluster76", "Ectoedemia sericopeza"))
res <- rbind(res, c("Drepanidae_cluster4", "Achlya flavicornis"))
res <- rbind(res, c("Pyralidae_cluster9", "Dioryctria simplicella"))
res <- rbind(res, c("Pyralidae_cluster21", "Plodia interpunctella"))
res <- rbind(res, c("Eriocraniidae_cluster2", "Dyseriocrania subpurpurella"))
res <- rbind(res, c("Epermeniidae_cluster1", "Epermenia chaerophyllella"))
res <- rbind(res, c("Bedelliidae_cluster1", "Bedellia somnulentella"))

# These are apparently correct species filtered away as numts by version 1 of the IBA pipeline
res <- rbind(res, c("unclassified.Lepidoptera_cluster9", "Stigmella confusella"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster10", "Lycaena virgaureae"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster12", "Charissa obscurata"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster13", "Stigmella lapponica"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster14", "Trifurcula cryptella"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster15", "Archips betulanus"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster16", "Stigmella anomalella"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster17", "Philedonides lunana"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster19", "Parornix traugotti"))
res <- rbind(res, c("unclassified.Lepidoptera_cluster20", "Stigmella pretiosa"))

# These are likely correct species hits among OTUs not identified to species or BIN
res <- rbind(res, c("Elachistidae_cluster1", "Elachista exactella"))
res <- rbind(res, c("Crambidae_cluster3", "Agriphila straminella"))
res <- rbind(res, c("Tortricidae_cluster21", "Apotomis inundana"))
res <- rbind(res, c("Tortricidae_cluster46", "Phiaris palustrana"))
res <- rbind(res, c("Nymphalidae_cluster3", "Lasiommata megera"))
res <- rbind(res, c("Argyresthiidae_cluster5", "Argyresthia pruniella"))
res <- rbind(res, c("Geometridae_cluster62", "Dysstroma latefasciata"))
res <- rbind(res, c("Noctuidae_cluster55", "Hyppa rectilinea"))
res <- rbind(res, c("Elachistidae_cluster17", "Elachista humilis"))
res <- rbind(res, c("Noctuidae_cluster60", "Lacanobia thalassina"))
res <- rbind(res, c("Elachistidae_cluster20", "Agonopterix alstromeriana"))
res <- rbind(res, c("Lypusidae_cluster4", "Agnoea flavifrontella"))
res <- rbind(res, c("Lypusidae_cluster5", "Lypusa maurella"))
res <- rbind(res, c("Nepticulidae_cluster8", "Stigmella myrtillella"))
res <- rbind(res, c("Noctuidae_cluster84", "Lycophotia porphyrea"))
res <- rbind(res, c("Coleophoridae_cluster23", "Coleophora otidipennella"))
res <- rbind(res, c("Tortricidae_cluster148", "Acleris hastiana"))
res <- rbind(res, c("Noctuidae_cluster95", "Apamea rubrirena"))
res <- rbind(res, c("Nepticulidae_cluster13", "Stigmella lappovimella"))
res <- rbind(res, c("Crambidae_cluster33", "Catoptria permutatella"))
res <- rbind(res, c("Coleophoridae_cluster31", "Coleophora alnifoliae"))
res <- rbind(res, c("Tortricidae_cluster179", "Eucosma aspidiscana"))
res <- rbind(res, c("Coleophoridae_cluster38", "Coleophora serratella"))
res <- rbind(res, c("Nepticulidae_cluster20", "Stigmella luteella"))
res <- rbind(res, c("Noctuidae_cluster127", "Euxoa nigricans"))
res <- rbind(res, c("Gracillariidae_cluster47", "Phyllonorycter oxyacanthae"))
res <- rbind(res, c("Nepticulidae_cluster25", "Stigmella glutinosae"))
res <- rbind(res, c("Coleophoridae_cluster45", "Coleophora betulella"))
res <- rbind(res, c("Nepticulidae_cluster29", "Stigmella salicis"))
res <- rbind(res, c("Praydidae_cluster1", "Prays ruficeps"))
res <- rbind(res, c("Elachistidae_cluster59", "Elachista zernyi"))
res <- rbind(res, c("Nepticulidae_cluster64", "Stigmella anomalella"))
res <- rbind(res, c("Lycaenidae_cluster11", "Aricia artaxerxes"))
res <- rbind(res, c("Geometridae_cluster200", "Cyclophora porata"))
res <- rbind(res, c("Nepticulidae_cluster75", "Stigmella prunetorum"))

# Match against GBIF taxonomy
library("rgbif")
E <- name_backbone_checklist(res$dyntaxa_name)
res$gbif_name <- E$species

# Fix a synonym that is not resolved correctly by the GBIF name resolver without author info
res$gbif_name[which(res$dyntaxa_name=="Swammerdamia caesiella")] <- "Swammerdamia heroldella"

write.table(res, "../output_tables/summary_manual_dyntaxa_annotations.tsv")

